import React, { useState } from 'react';
import { 
  ArrowLeft, 
  ShieldAlert, 
  AlertTriangle, 
  CheckCircle2, 
  Copy, 
  Check, 
  Trash2, 
  Share2, 
  Download, 
  FileText, 
  Terminal, 
  ExternalLink, 
  Clock, 
  ChevronDown, 
  ChevronUp, 
  Tag, 
  Sparkles, 
  Cpu, 
  Database,
  Save,
  Activity,
  Layers,
  ShieldCheck
} from 'lucide-react';
import { Investigation, ThreatSeverity, IncidentStatus, ResponseAction } from '../types';
import { updateInvestigationInFirestore, deleteInvestigationFromFirestore } from '../lib/firebase';

interface InvestigationDetailViewProps {
  investigation: Investigation;
  onBack: () => void;
  onDeleted: (id: string) => void;
  onUpdated: (updated: Investigation) => void;
}

export const InvestigationDetailView: React.FC<InvestigationDetailViewProps> = ({
  investigation,
  onBack,
  onDeleted,
  onUpdated,
}) => {
  const [copiedKey, setCopiedKey] = useState<string | null>(null);
  const [notes, setNotes] = useState(investigation.notes || '');
  const [status, setStatus] = useState<IncidentStatus>(investigation.status || 'investigated');
  const [savingNotes, setSavingNotes] = useState(false);
  const [notesSaved, setNotesSaved] = useState(false);
  const [showRawLogs, setShowRawLogs] = useState(false);
  const [activeIocFilter, setActiveIocFilter] = useState<string>('All');
  const [deleting, setDeleting] = useState(false);

  const { analysis } = investigation;

  const handleCopy = (text: string, key: string) => {
    navigator.clipboard.writeText(text);
    setCopiedKey(key);
    setTimeout(() => setCopiedKey(null), 2000);
  };

  const handleStatusChange = async (newStatus: IncidentStatus) => {
    setStatus(newStatus);
    try {
      await updateInvestigationInFirestore(investigation.userId, investigation.id, {
        status: newStatus,
      });
      onUpdated({ ...investigation, status: newStatus });
    } catch (err) {
      console.error('Failed to update status:', err);
    }
  };

  const handleSaveNotes = async () => {
    setSavingNotes(true);
    try {
      await updateInvestigationInFirestore(investigation.userId, investigation.id, {
        notes,
      });
      setNotesSaved(true);
      setTimeout(() => setNotesSaved(false), 2500);
      onUpdated({ ...investigation, notes });
    } catch (err) {
      console.error('Failed to save notes:', err);
    } finally {
      setSavingNotes(false);
    }
  };

  const handleDelete = async () => {
    if (!window.confirm('Are you sure you want to delete this incident investigation from Cloud Firestore?')) {
      return;
    }
    setDeleting(true);
    try {
      await deleteInvestigationFromFirestore(investigation.userId, investigation.id);
      onDeleted(investigation.id);
    } catch (err) {
      console.error('Failed to delete investigation:', err);
      setDeleting(false);
    }
  };

  const handleExportMarkdown = () => {
    const mdContent = `# SentinelAI Incident Investigation Report
**Title**: ${investigation.title}
**Date**: ${new Date(investigation.createdAt).toUTCString()}
**Threat Severity**: ${analysis.threatSeverity} (Score: ${analysis.threatScore}/100)
**Likely Attack Type**: ${analysis.likelyAttackType}
**Confidence Level**: ${analysis.confidenceLevel} (${analysis.confidenceScore}%)
**Status**: ${status}

---
## Executive Summary
${analysis.executiveSummary}

## Technical Anomaly Breakdown
${analysis.whySuspicious}

## Attack Storyline
${analysis.attackStoryline.map((s) => `${s.step}. [${s.phase}] (${s.timestamp}): ${s.description} ${s.techniqueId ? `[${s.techniqueId}]` : ''}`).join('\n')}

## Indicators of Compromise (IoCs)
${analysis.indicatorsOfCompromise.map((ioc) => `- [${ioc.type}] ${ioc.value} (${ioc.reputation}) - ${ioc.context}`).join('\n')}

## Recommended Response Actions
${analysis.recommendedResponseActions.map((r) => `### [${r.priority}] ${r.action}\n${r.description}\n${r.suggestedCommand ? `\`\`\`bash\n${r.suggestedCommand}\n\`\`\`` : ''}`).join('\n\n')}

## Analyst Notes
${notes || 'None recorded.'}

---
Generated by SentinelAI SOC Investigator (${investigation.modelUsed || analysis.modelUsed || 'Gemini Flash'} + Cloud Firestore)
`;
    const blob = new Blob([mdContent], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `incident-report-${investigation.id}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const getSeverityBadge = (severity: ThreatSeverity) => {
    switch (severity) {
      case 'Critical':
        return (
          <div className="flex items-center space-x-2 px-3 py-1.5 rounded-xl bg-red-950/80 border border-red-700/80 text-red-300">
            <span className="w-2.5 h-2.5 rounded-full bg-red-500 animate-ping"></span>
            <span className="font-bold text-sm">Critical Severity</span>
          </div>
        );
      case 'High':
        return (
          <div className="flex items-center space-x-2 px-3 py-1.5 rounded-xl bg-orange-950/80 border border-orange-700/80 text-orange-300">
            <span className="w-2.5 h-2.5 rounded-full bg-orange-500"></span>
            <span className="font-bold text-sm">High Severity</span>
          </div>
        );
      case 'Medium':
        return (
          <div className="flex items-center space-x-2 px-3 py-1.5 rounded-xl bg-yellow-950/80 border border-yellow-700/80 text-yellow-300">
            <span className="w-2.5 h-2.5 rounded-full bg-yellow-500"></span>
            <span className="font-bold text-sm">Medium Severity</span>
          </div>
        );
      case 'Low':
        return (
          <div className="flex items-center space-x-2 px-3 py-1.5 rounded-xl bg-emerald-950/80 border border-emerald-700/80 text-emerald-300">
            <span className="w-2.5 h-2.5 rounded-full bg-emerald-500"></span>
            <span className="font-bold text-sm">Low Severity</span>
          </div>
        );
    }
  };

  const iocTypes = ['All', ...Array.from(new Set(analysis.indicatorsOfCompromise.map((i) => i.type)))];
  const filteredIocs = activeIocFilter === 'All'
    ? analysis.indicatorsOfCompromise
    : analysis.indicatorsOfCompromise.filter((i) => i.type === activeIocFilter);

  return (
    <div className="space-y-8 pb-16 max-w-6xl mx-auto">
      {/* Top Header & Actions */}
      <div className="space-y-4 border-b border-slate-800 pb-6">
        <div className="flex flex-wrap items-center justify-between gap-4">
          <button
            id="btn-back-to-list"
            onClick={onBack}
            className="inline-flex items-center space-x-2 text-xs font-semibold text-slate-400 hover:text-cyan-300 transition-colors cursor-pointer"
          >
            <ArrowLeft className="w-4 h-4" />
            <span>Back to Dashboard</span>
          </button>

          <div className="flex flex-wrap items-center gap-2">
            {/* Status selector */}
            <div className="flex items-center space-x-2 bg-slate-900 border border-slate-800 px-3 py-1.5 rounded-xl text-xs">
              <span className="text-slate-400">Status:</span>
              <select
                id="select-incident-status"
                value={status}
                onChange={(e) => handleStatusChange(e.target.value as IncidentStatus)}
                className="bg-transparent text-cyan-300 font-semibold focus:outline-none cursor-pointer"
              >
                <option value="investigated" className="bg-slate-900 text-white">Investigated</option>
                <option value="contained" className="bg-slate-900 text-white">Contained</option>
                <option value="remediated" className="bg-slate-900 text-white">Remediated</option>
                <option value="closed" className="bg-slate-900 text-white">Closed</option>
              </select>
            </div>

            {/* Export Markdown */}
            <button
              onClick={handleExportMarkdown}
              title="Download Incident Report"
              className="px-3 py-1.5 rounded-xl bg-slate-900 hover:bg-slate-800 border border-slate-700 text-slate-200 text-xs font-medium flex items-center space-x-1.5 transition-colors cursor-pointer"
            >
              <Download className="w-3.5 h-3.5 text-cyan-400" />
              <span>Export Report</span>
            </button>

            {/* Delete button */}
            <button
              onClick={handleDelete}
              disabled={deleting}
              title="Delete from Firestore"
              className="p-2 rounded-xl bg-slate-900 hover:bg-red-950/60 border border-slate-800 hover:border-red-800 text-slate-400 hover:text-red-400 transition-colors cursor-pointer disabled:opacity-50"
            >
              <Trash2 className="w-4 h-4" />
            </button>
          </div>
        </div>

        {/* Title, Severity & Attack Type Hero */}
        <div className="flex flex-col md:flex-row md:items-start justify-between gap-6">
          <div className="space-y-2 flex-1">
            <div className="flex flex-wrap items-center gap-2">
              {getSeverityBadge(analysis.threatSeverity)}
              <span className="text-xs font-mono uppercase px-2.5 py-1 rounded-lg bg-slate-900 border border-slate-800 text-cyan-400">
                {investigation.incidentType.replace('_', ' ')}
              </span>
              {investigation.isDemoSample && (
                <span className="text-xs font-mono px-2 py-0.5 rounded-lg bg-amber-950/70 text-amber-300 border border-amber-800">
                  DEMO DATA
                </span>
              )}
            </div>

            <h1 className="text-2xl sm:text-3xl font-extrabold text-white tracking-tight">
              {investigation.title}
            </h1>

            <div className="flex items-center space-x-2 text-cyan-300 text-base font-semibold">
              <Activity className="w-4 h-4 text-cyan-400" />
              <span>Likely Attack: {analysis.likelyAttackType}</span>
            </div>

            <div className="flex flex-wrap items-center gap-3 text-xs text-slate-400 pt-1">
              <span className="flex items-center space-x-1">
                <Clock className="w-3.5 h-3.5 text-slate-500" />
                <span>Logged {new Date(investigation.createdAt).toLocaleString()}</span>
              </span>
              <span className="text-slate-600">•</span>
              <span className="font-mono text-slate-400">
                ID: {investigation.id}
              </span>
              {(investigation.modelUsed || analysis.modelUsed) && (
                <>
                  <span className="text-slate-600">•</span>
                  <span className="inline-flex items-center space-x-1 px-2 py-0.5 rounded bg-slate-900 border border-slate-800 text-cyan-300 font-mono text-[11px]">
                    <Sparkles className="w-3 h-3 text-cyan-400" />
                    <span>{investigation.modelUsed || analysis.modelUsed}</span>
                  </span>
                </>
              )}
            </div>
          </div>

          {/* Threat Metric Card */}
          <div className="p-4 rounded-2xl bg-slate-900/90 border border-slate-800 flex items-center gap-6 self-start">
            <div className="text-center">
              <span className="text-[10px] font-semibold uppercase text-slate-400 tracking-wider">Threat Score</span>
              <div className={`text-3xl font-extrabold mt-0.5 ${
                analysis.threatScore >= 90 ? 'text-red-400' :
                analysis.threatScore >= 70 ? 'text-orange-400' :
                analysis.threatScore >= 40 ? 'text-yellow-400' : 'text-emerald-400'
              }`}>
                {analysis.threatScore}
                <span className="text-xs font-normal text-slate-500">/100</span>
              </div>
            </div>

            <div className="h-10 w-[1px] bg-slate-800"></div>

            <div className="text-center">
              <span className="text-[10px] font-semibold uppercase text-slate-400 tracking-wider">AI Confidence</span>
              <div className="text-3xl font-extrabold text-cyan-400 mt-0.5">
                {analysis.confidenceScore}%
              </div>
              <span className="text-[10px] font-mono text-slate-400">{analysis.confidenceLevel} Confidence</span>
            </div>
          </div>
        </div>
      </div>

      {/* Grid: Executive Summary & Technical Anomaly */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Executive Summary */}
        <div className="p-5 rounded-2xl bg-slate-900/70 border border-slate-800 space-y-3">
          <h3 className="text-sm font-bold text-white uppercase tracking-wider flex items-center gap-2">
            <FileText className="w-4 h-4 text-cyan-400" />
            <span>Executive Briefing</span>
          </h3>
          <p className="text-sm text-slate-300 leading-relaxed">
            {analysis.executiveSummary}
          </p>

          {analysis.attackVector && (
            <div className="pt-2 border-t border-slate-800/80 text-xs text-slate-400">
              <span className="font-semibold text-slate-300">Attack Vector: </span>
              <span>{analysis.attackVector}</span>
            </div>
          )}
        </div>

        {/* Why Suspicious Deep Dive */}
        <div className="p-5 rounded-2xl bg-slate-900/70 border border-slate-800 space-y-3">
          <h3 className="text-sm font-bold text-white uppercase tracking-wider flex items-center gap-2">
            <AlertTriangle className="w-4 h-4 text-amber-400" />
            <span>Why This Activity Is Suspicious</span>
          </h3>
          <p className="text-sm text-slate-300 leading-relaxed">
            {analysis.whySuspicious}
          </p>

          {analysis.affectedAssets && analysis.affectedAssets.length > 0 && (
            <div className="pt-2 border-t border-slate-800/80 flex flex-wrap items-center gap-1.5 text-xs">
              <span className="font-semibold text-slate-300">Assets:</span>
              {analysis.affectedAssets.map((asset, idx) => (
                <span key={idx} className="font-mono text-[11px] px-2 py-0.5 rounded bg-slate-800 text-slate-300 border border-slate-700">
                  {asset}
                </span>
              ))}
            </div>
          )}
        </div>
      </div>

      {/* Attack / Incident Storyline Section */}
      <div className="p-6 rounded-2xl bg-slate-900/80 border border-slate-800 space-y-5">
        <div className="flex items-center justify-between">
          <h3 className="text-base font-bold text-white flex items-center gap-2">
            <Activity className="w-5 h-5 text-cyan-400" />
            <span>Chronological Attack Storyline</span>
          </h3>
          <span className="text-xs text-slate-400 font-mono">
            {analysis.attackStoryline.length} Event Phases Reconstructed
          </span>
        </div>

        <div className="relative pl-6 space-y-6 before:absolute before:left-2 before:top-2 before:bottom-2 before:w-0.5 before:bg-gradient-to-b before:from-cyan-500 before:via-blue-500 before:to-slate-800">
          {analysis.attackStoryline.map((item, idx) => (
            <div key={idx} className="relative group">
              {/* Timeline marker */}
              <div className="absolute -left-[27px] top-1.5 w-3.5 h-3.5 rounded-full bg-slate-950 border-2 border-cyan-400 group-hover:scale-125 transition-transform" />

              <div className="p-4 rounded-xl bg-slate-950/70 border border-slate-800/90 space-y-1.5">
                <div className="flex flex-wrap items-center justify-between gap-2">
                  <div className="flex items-center space-x-2">
                    <span className="text-xs font-mono font-bold text-cyan-400">
                      Step {item.step || idx + 1}
                    </span>
                    <span className="text-xs font-semibold px-2 py-0.5 rounded bg-cyan-950/70 border border-cyan-800 text-cyan-300">
                      {item.phase}
                    </span>
                    {item.techniqueId && (
                      <span className="text-[11px] font-mono px-1.5 py-0.2 rounded bg-slate-800 text-slate-300 border border-slate-700">
                        {item.techniqueId}
                      </span>
                    )}
                  </div>
                  <span className="text-[11px] font-mono text-slate-500">
                    {item.timestamp}
                  </span>
                </div>

                <p className="text-sm text-slate-200 leading-relaxed">
                  {item.description}
                </p>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* MITRE ATT&CK Techniques Grid */}
      {analysis.mitreAttackTechniques && analysis.mitreAttackTechniques.length > 0 && (
        <div className="p-6 rounded-2xl bg-slate-900/60 border border-slate-800 space-y-4">
          <h3 className="text-sm font-bold text-white uppercase tracking-wider flex items-center gap-2">
            <Layers className="w-4 h-4 text-cyan-400" />
            <span>Correlated MITRE ATT&CK Matrix Techniques</span>
          </h3>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
            {analysis.mitreAttackTechniques.map((tech, idx) => (
              <div key={idx} className="p-3 rounded-xl bg-slate-950/80 border border-slate-800 space-y-1">
                <div className="flex items-center justify-between">
                  <span className="text-xs font-mono font-bold text-cyan-400">
                    {tech.id}
                  </span>
                  <span className="text-[10px] font-mono text-slate-400 truncate max-w-[140px]">
                    {tech.tactic}
                  </span>
                </div>
                <p className="text-xs font-medium text-white">{tech.name}</p>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Indicators of Compromise (IoCs) Explorer */}
      <div className="p-6 rounded-2xl bg-slate-900/80 border border-slate-800 space-y-4">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
          <div>
            <h3 className="text-base font-bold text-white flex items-center gap-2">
              <ShieldAlert className="w-5 h-5 text-red-400" />
              <span>Extracted Indicators of Compromise (IoCs)</span>
            </h3>
            <p className="text-xs text-slate-400 mt-0.5">
              Identified forensic artifacts across IP addresses, domains, hashes, and commands.
            </p>
          </div>

          {/* Type filter pills */}
          <div className="flex flex-wrap gap-1.5">
            {iocTypes.map((type) => (
              <button
                key={type}
                onClick={() => setActiveIocFilter(type)}
                className={`px-2.5 py-1 rounded-lg text-xs font-mono transition-colors cursor-pointer ${
                  activeIocFilter === type
                    ? 'bg-cyan-500 text-slate-950 font-bold'
                    : 'bg-slate-800 text-slate-300 hover:bg-slate-700'
                }`}
              >
                {type}
              </button>
            ))}
          </div>
        </div>

        <div className="overflow-hidden rounded-xl border border-slate-800 bg-slate-950">
          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs">
              <thead className="bg-slate-900 text-slate-400 uppercase tracking-wider font-mono text-[11px] border-b border-slate-800">
                <tr>
                  <th className="px-4 py-3">Type</th>
                  <th className="px-4 py-3">Indicator Value</th>
                  <th className="px-4 py-3">Reputation</th>
                  <th className="px-4 py-3">Context / Investigation Finding</th>
                  <th className="px-4 py-3 text-right">Action</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-800 font-mono">
                {filteredIocs.map((ioc, idx) => (
                  <tr key={idx} className="hover:bg-slate-900/50 transition-colors">
                    <td className="px-4 py-3 text-cyan-400 font-bold whitespace-nowrap">
                      {ioc.type}
                    </td>
                    <td className="px-4 py-3 text-white font-medium select-all break-all max-w-xs">
                      {ioc.value}
                    </td>
                    <td className="px-4 py-3 whitespace-nowrap">
                      <span className={`px-2 py-0.5 rounded text-[10px] font-bold ${
                        ioc.reputation === 'Malicious'
                          ? 'bg-red-950/80 text-red-300 border border-red-800'
                          : ioc.reputation === 'Suspicious'
                          ? 'bg-orange-950/80 text-orange-300 border border-orange-800'
                          : 'bg-slate-800 text-slate-300'
                      }`}>
                        {ioc.reputation}
                      </span>
                    </td>
                    <td className="px-4 py-3 text-slate-300 font-sans max-w-sm">
                      {ioc.context}
                    </td>
                    <td className="px-4 py-3 text-right whitespace-nowrap">
                      <button
                        onClick={() => handleCopy(ioc.value, `ioc-${idx}`)}
                        className="p-1.5 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-300 hover:text-white transition-colors cursor-pointer"
                        title="Copy IoC value"
                      >
                        {copiedKey === `ioc-${idx}` ? (
                          <Check className="w-3.5 h-3.5 text-emerald-400" />
                        ) : (
                          <Copy className="w-3.5 h-3.5" />
                        )}
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </div>

      {/* Recommended Response Actions Playbook */}
      <div className="p-6 rounded-2xl bg-slate-900/80 border border-slate-800 space-y-5">
        <div>
          <h3 className="text-base font-bold text-white flex items-center gap-2">
            <ShieldCheck className="w-5 h-5 text-emerald-400" />
            <span>Recommended Incident Response Playbook</span>
          </h3>
          <p className="text-xs text-slate-400 mt-0.5">
            Prioritized tactical mitigation runbook synthesized by Gemini for SOC responders.
          </p>
        </div>

        <div className="space-y-3">
          {analysis.recommendedResponseActions.map((action, idx) => (
            <div
              key={idx}
              className="p-4 rounded-xl bg-slate-950/80 border border-slate-800/90 space-y-2.5"
            >
              <div className="flex flex-wrap items-center justify-between gap-2">
                <div className="flex items-center space-x-2">
                  <span className={`text-[11px] font-mono px-2 py-0.5 rounded font-bold ${
                    action.priority.startsWith('P1')
                      ? 'bg-red-950 text-red-400 border border-red-800'
                      : action.priority.startsWith('P2')
                      ? 'bg-orange-950 text-orange-400 border border-orange-800'
                      : 'bg-yellow-950 text-yellow-400 border border-yellow-800'
                  }`}>
                    {action.priority}
                  </span>
                  <h4 className="text-sm font-semibold text-white">{action.action}</h4>
                </div>
              </div>

              <p className="text-xs text-slate-300 leading-relaxed">
                {action.description}
              </p>

              {action.suggestedCommand && (
                <div className="relative rounded-lg bg-slate-900 border border-slate-800 p-2.5 flex items-center justify-between text-xs font-mono text-cyan-300">
                  <span className="overflow-x-auto pr-4 select-all">
                    $ {action.suggestedCommand}
                  </span>
                  <button
                    onClick={() => handleCopy(action.suggestedCommand!, `cmd-${idx}`)}
                    className="p-1 rounded bg-slate-800 hover:bg-slate-700 text-slate-300 hover:text-white transition-colors cursor-pointer shrink-0"
                    title="Copy command"
                  >
                    {copiedKey === `cmd-${idx}` ? (
                      <Check className="w-3.5 h-3.5 text-emerald-400" />
                    ) : (
                      <Copy className="w-3.5 h-3.5" />
                    )}
                  </button>
                </div>
              )}
            </div>
          ))}
        </div>
      </div>

      {/* SOC Analyst Notes (Synced to Cloud Firestore) */}
      <div className="p-6 rounded-2xl bg-slate-900/80 border border-slate-800 space-y-3">
        <div className="flex items-center justify-between">
          <div>
            <h3 className="text-base font-bold text-white flex items-center gap-2">
              <Database className="w-4 h-4 text-cyan-400" />
              <span>SOC Analyst Investigation Notes</span>
            </h3>
            <p className="text-xs text-slate-400">
              Document your manual triage observations, ticket IDs, and escalation notes. Automatically stored in Cloud Firestore.
            </p>
          </div>

          <button
            id="btn-save-notes"
            onClick={handleSaveNotes}
            disabled={savingNotes}
            className="px-3.5 py-1.5 rounded-xl bg-cyan-600 hover:bg-cyan-500 text-white text-xs font-semibold flex items-center space-x-1.5 transition-colors cursor-pointer disabled:opacity-50"
          >
            <Save className="w-3.5 h-3.5" />
            <span>{savingNotes ? 'Saving...' : notesSaved ? 'Saved to Firestore!' : 'Save Notes'}</span>
          </button>
        </div>

        <textarea
          rows={4}
          value={notes}
          onChange={(e) => setNotes(e.target.value)}
          placeholder="Enter investigation log notes, IR ticket references (e.g. INC-94812), forensic findings, or containment confirmation..."
          className="w-full p-3.5 rounded-xl bg-slate-950 border border-slate-800 text-xs text-slate-200 placeholder-slate-600 focus:outline-none focus:border-cyan-500/60 resize-y"
        />
      </div>

      {/* Collapsible Raw Telemetry Viewer */}
      <div className="rounded-2xl border border-slate-800 bg-slate-900/50 overflow-hidden">
        <button
          onClick={() => setShowRawLogs(!showRawLogs)}
          className="w-full px-6 py-4 flex items-center justify-between text-left hover:bg-slate-900/80 transition-colors cursor-pointer"
        >
          <span className="text-xs font-semibold text-slate-300 flex items-center gap-2">
            <Terminal className="w-4 h-4 text-cyan-400" />
            <span>Raw Submitted Incident Telemetry & Artifacts</span>
          </span>
          <div className="flex items-center space-x-2 text-xs text-slate-400">
            <span>{showRawLogs ? 'Collapse' : 'Expand'}</span>
            {showRawLogs ? <ChevronUp className="w-4 h-4" /> : <ChevronDown className="w-4 h-4" />}
          </div>
        </button>

        {showRawLogs && (
          <div className="p-4 bg-slate-950 border-t border-slate-800">
            <pre className="p-4 rounded-xl bg-slate-900/80 border border-slate-800/80 font-mono text-xs text-slate-300 overflow-x-auto whitespace-pre-wrap leading-relaxed max-h-96">
              {investigation.rawIncident}
            </pre>
          </div>
        )}
      </div>
    </div>
  );
};
